### PR TITLE
Update Formatting and Dependencies + Python 3 Support

### PR DESCRIPTION
**Pull request by TariqAHassan**
I've gone through and tried to reformat some of the code (and examples).
There is still more to be done, but this should move `nsgt` towards being easier to maintain and update.

@carlthome.  This may interest you (given [PR13](https://github.com/grrrr/nsgt/pull/13)). If you're interested in refactoring `nsgt` further, let me know. The next logical step would be to simply rewrite some of the larger methods and functions.

Edit: I am aware some tests fail -- will try to fix that soon.

### CODE REVIEW

**Comment by grrrr** [comment]
Hi Tariq, thanks for your contributions.
Please note that i will not take into account your renaming of functions, etc., simply because it breaks my (and probably others') code dependent on NSGT.
In order to be able to integrate your changes, i would like to encourage you to separate your contributions. First, the refactoring, second the code reformatting, in separate branches.
It would make it a lot easier to review your code.
best, Thomas

**Comment by grrrr** [comment]
Also, please don't delete functions if they seems unused. They might be used in dependent code or future improvements of NSGT.

**Comment by TariqAHassan** [comment]
1. Respectfully, some of the names should change to be more pythonic and idiomatic (i.e., make it easier for others to modify your code). However, renaming a few of classes/methods does not need to cause broken code -- I can make an update to ensure that old code still works like nothing has changed (which we can also write tests for).

2. I believe the only function I suggested to be depreciated was/is `audio.SndWriter`. It is not used anywhere else in the project (I did an exhaustive search using PyCharm), the only exception is in */examples* where its functionality can easily be supplanted by `librosa` (meaning less code to be maintained).

3. Yeah, I'm more than happy to break up the refactoring and formatting. However, I will just note that the vast majority (95%+) of the changes are simply formatting.

Best,
Tariq

**Comment by grrrr** [comment]
Hi, i have merged #13 by @carlthome. It would be great if you could rebase your changes on the new HEAD. As said, i am not happy with stylistic "corrections" and name changes. Nevertheless, i am thankful for your contributions and will review them for integration.

**Pull request closed without merging**
